### PR TITLE
Java 11 readiness: Use recommended build configurations

### PR DESCRIPTION
**Pull request by batmat**
For Java 11 readiness, apply recommended configuration:
https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime

And fixing what was revealed through this.

@jenkinsci/java11-support

### CODE REVIEW

**Comment by batmat** [comment]
Picked up commits from https://github.com/jenkinsci/blueocean-autofavorite-plugin/pull/19

**Comment by alecharp** [comment]
Thanks. Sadly, a test is failing, but even with the previous code on the normal core version , it is not successful (Java 8 or Java 11). Will try to see what is happening.

**Comment by alecharp** [comment]
Test failure since the parent-pom upgrade. Digging.

**Comment by alecharp** [comment]
@batmat There are newer commits to grab on #19 to solve this.

**Comment by batmat** [comment]
Grabbed.

**Comment by michaelneale** [comment]
LGTM from what I *remember* this should do.

**Comment by michaelneale** [comment]
@batmat want to add other to owners for this to deploy? as it isn't really clear who deploys this (it rarely needs changing)

**Comment by batmat** [comment]
@michaelneale apparently https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-blueocean-autofavorite.yml, so I requested a review here from the maintainers I _think_ are still roughly active here :)

**Comment by halkeye** [comment]
Imma gonna merge, then release while i'm at the gym

**Comment by halkeye** [comment]
wait i'm a maintainer but i can't write to this repo :)

**Comment by halkeye** [comment]
@batmat @alecharp can you update https://wiki.jenkins.io/display/JENKINS/Blue+Ocean+Autofavorite+Plugin with what you usually do for java11? its the only thing in this realease.

**Comment by halkeye** [comment]
https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/blueocean-autofavorite/1.2.4/blueocean-autofavorite-1.2.4.hpi

**Comment by alecharp** [comment]
thank you @halkeye !

**Pull request merged**
