### PR TITLE
Upgrade to git 3.6.0 and other workflow-* plugins

### PR DESCRIPTION
**Pull request by vivek**
@i386 @michaelneale @stephenc there is test failing in PCT. 

[This test](https://github.com/jenkinsci/blueocean-autofavorite-plugin/blob/36957e41b242da305fc55b88fa9589b6f527874c/src/test/java/io/jenkins/blueocean/autofavorite/FavoritingScmListenerTest.java#L43) creates a multi-branch project and expects [FavoritingScmListener.onCheckout()](https://github.com/jenkinsci/blueocean-autofavorite-plugin/blob/398fc00bc2d4b3caab4d62dd347a43147103ed6d/src/main/java/io/jenkins/blueocean/autofavorite/FavoritingScmListener.java#L47) to get called, but it never gets called and test fails.

This gets printed. Its missing logs from `FavoritingScmListener.onCheckout()`. 

```
=== Starting testAutoFavoriteForRegisteredUser(io.jenkins.blueocean.autofavorite.FavoritingScmListenerTest)
Nov 09, 2017 7:33:33 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: WorkflowMultiBranchProject #20171109.193330 branch indexing action completed: SUCCESS in 2.3 sec
Nov 09, 2017 7:33:36 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: WorkflowMultiBranchProject/master #1 completed: FAILURE
Nov 09, 2017 7:33:36 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: WorkflowMultiBranchProject/bob #1 completed: FAILURE
Nov 09, 2017 7:33:36 PM org.eclipse.jetty.server.AbstractConnector doStop
INFO: Stopped ServerConnector@a4add54{HTTP/1.1}{localhost:0}
Nov 09, 2017 7:33:36 PM org.eclipse.jetty.server.handler.ContextHandler doStop

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.jenkins.blueocean.autofavorite.FavoritingScmListenerTest.testAutoFavoriteForRegisteredUser(FavoritingScmListenerTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:533)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Before upgrade to git 3.6.0 and other workflow-* plugins it used to print:

```
Nov 09, 2017 7:23:45 PM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: WorkflowMultiBranchProject #20171109.192344 branch indexing action completed: SUCCESS in 1.5 sec
Nov 09, 2017 7:23:47 PM io.jenkins.blueocean.autofavorite.FavoritingScmListener onCheckout
INFO: Automatically favorited WorkflowMultiBranchProject/bob for jdumay
Nov 09, 2017 7:23:47 PM io.jenkins.blueocean.autofavorite.FavoritingScmListener onCheckout
INFO: Automatically favorited WorkflowMultiBranchProject/master for jdumay
Nov 09, 2017 7:23:48 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: WorkflowMultiBranchProject/bob #1 completed: FAILURE
Nov 09, 2017 7:23:48 PM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: WorkflowMultiBranchProject/master #1 completed: FAILURE
Nov 09, 2017 7:23:49 PM org.eclipse.jetty.server.AbstractConnector doStop
INFO: Stopped ServerConnector@1458ed9c{HTTP/1.1}{localhost:0}
Nov 09, 2017 7:23:49 PM org.eclipse.jetty.server.handler.ContextHandler doStop
```

@stephenc why would `SCMListener.onCheckout()` stopped getting called in this test after upgrading to git 3.6.0 and other workflow plugins?

### CODE REVIEW

**Comment by michaelneale** [comment]
looking good but looks like test errors

**Comment by vivek** [comment]
@michaelneale at present this PR demonstrates the failing test. I have spent enough time to try and fix it. No idea why the `SCMListener.onCheckout()` does get called.

**Comment by michaelneale** [comment]
@vivek ah my misunderstanding

**Comment by michaelneale** [comment]
ping @i386 any ideas?

**Comment by michaelneale** [comment]
`onCheckout` is a fairly major thing to not be called... so this looks like a bad bug somewhere (not sure if to do with auto fav - is this really the only plugin that uses that listener?

**Comment by vivek** [comment]
workflow-job, gitHub-branch-source, bitbucket-branch-source etc. provides SCMListener extension as well. Not sure if they have tests.

**Comment by stephenc** [comment]
Is lightweight checkout in play here?

**Comment by stephenc** [comment]
https://github.com/i386/feedle/blob/master/Jenkinsfile Looks to do an on-node checkout... so lightweight shouldn’t be an issue

**Comment by michaelneale** [comment]
I thought so too (and bet an iPhone X). 
Declarative should do a checkout on a node ... should.

**Comment by michaelneale** [comment]
@stephenc @vivek any more ideas here? Otherwise this looks like a bad regression in the git plugin?

**Comment by vivek** [comment]
Further investigation tells me, there wasn't any regression as such caused by git plugin. 

The test git repo master branch has declarative pipeline. however there is missing test dependency on declarative. Adding that along wither other latest workflow libraries fixes this failing test.

**Comment by michaelneale** [comment]
Woah amazing @vivek! 

Once again dependencies bite (it only worked by luck in this case). 

:bee: 

@i386 want to merge and cut a release of this sometime?

**Comment by michaelneale** [comment]
@vivek I hope you were ready for this to be merged and released - as it is done ;)

**Pull request merged**
